name: Simple CI/CD for Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4
  
    -name: Print Directory Structure
        run:ls -R

      - name:Print Current Directory
        run:pwd

      - name:Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false
        working-directory: ${{ github.workspace }}/tp-2
        
      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Print success message
        run: echo "Buil
