name: Simple CI/CD for Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false
        working-directory: 'tp-2/demo (2)' 

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: 'tp-2/demo (2)/target/*.jar'

      - name: Print success message
        run: echo "Build and tests completed successfully!"
